# Nexus server nginx configuration file
events {
    worker_connections 4096; ## Default: 1024
}
http {
    sendfile                on;
    tcp_nopush              on;
    tcp_nodelay             on;
    keepalive_timeout       65s;
    types_hash_max_size     2048;

    include "D:/ANSYS Inc/ANSYS Student/v252/CEI/apex252/machines/win64/nginx/conf/mime.types";
    default_type application/octet-stream;

    upstream localhost {
        least_conn;
        server 127.0.0.1:21712;
    }

    server {
        server_name 127.0.0.1;
        #access_log off;
        listen 15412;
        proxy_read_timeout 300s;
        keepalive_timeout 90s;
        client_max_body_size 5000M;
        client_header_buffer_size 4096k;
        location /media/ {
            root "D:/normal_shock/CompressionCorner_files/dp0/FFF/Fluent/FluentReportServer";
        }
        location /static/ {
             root "D:/ANSYS Inc/ANSYS Student/v252/CEI/nexus252/django";
        }
        location /ansys252/ {
             root "D:/ANSYS Inc/ANSYS Student/v252/CEI/nexus252";
        }
        location /ansys/ {
             try_files $uri $uri/ @ansys252;
        }
        location @ansys252 {
             rewrite ^/ansys(/.*)$ /ansys252$1 last;
        }
        location / {
             proxy_pass http://localhost;
             proxy_pass_request_headers on;
             proxy_set_header X-Forwarded-Host $host:$server_port;
             proxy_set_header X-Forwarded-Proto $scheme;
        }

    }
}
